import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "linked in post generator",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#0A66C2]`}>
        
          {children}
        
          </body>
    </html>
  );
}
