import { Inter } from "next/font/google";
import "@/styles/globals.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "linked in post generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#D9D9D9]`}>
        
          {children}
        
          </body>
    </html>
  );
}
